jobs:
  build:
    if: github.repository == 'bazelbuild/bazel-buildfarm'
    name: Build Base Buildfarm Worker Image
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Login to Bazelbuild Docker Hub
      uses: docker/login-action@v3
      with:
        password: ${{ secrets.BAZELBUILD_DOCKERHUB_TOKEN }}
        username: ${{ secrets.BAZELBUILD_DOCKERHUB_USERNAME }}
    - continue-on-error: true
      name: Build Jammy Docker image
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: .
        file: ./ci/base-worker-image/jammy/Dockerfile
        push: false
        tags: bazelbuild/buildfarm-worker-base:jammy
    - continue-on-error: true
      name: Build Mantic Docker image
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: .
        file: ./ci/base-worker-image/mantic/Dockerfile
        push: false
        tags: bazelbuild/buildfarm-worker-base:mantic
name: Build and Push Base Buildfarm Worker Images
on:
  repository_dispatch:
    types: trigger-ga___buildfarm-worker-base-build-and-deploy.yml
