env:
  CHART_ROOT: kubernetes/helm-charts/buildfarm
jobs:
  lint:
    name: Lint Helm Chart
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      id: helm-lint
      name: Lint Helm Chart
      run: 'set -ex

        helm dep up "${CHART_ROOT}"

        helm lint "${CHART_ROOT}"'
name: Lint Helm Chart
on:
  repository_dispatch:
    types: trigger-ga___buildfarm-helm-chart-lint.yml
