jobs:
  build:
    if: github.repository == 'bazelbuild/bazel-buildfarm'
    name: Build Buildfarm Images
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: bazelbuild/setup-bazelisk@v2
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Login to Bazelbuild Docker Hub
      uses: docker/login-action@v3
      with:
        password: ${{ secrets.BAZELBUILD_DOCKERHUB_TOKEN }}
        username: ${{ secrets.BAZELBUILD_DOCKERHUB_USERNAME }}
    - continue-on-error: true
      id: buildAndPushServerImage
      name: Build Server Image
      run: bazel run public_push_buildfarm-server --define release_version=${{ github.event.release.tag_name
        }}
    - continue-on-error: true
      id: buildAndPushWorkerImage
      name: Build Worker Image
      run: bazel run public_push_buildfarm-worker --define release_version=${{ github.event.release.tag_name
        }}
name: Build and Push Buildfarm Releases
on:
  repository_dispatch:
    types: trigger-ga___buildfarm-release-build-and-deploy.yml
