jobs:
  build_and_deploy:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        path: vendor/bundle
        restore-keys: '${{ runner.os }}-gems-

          '
    - continue-on-error: true
      uses: jeffreytse/jekyll-deploy-action@v0.5.0
      with:
        actor: ''
        branch: gh-pages
        bundler_ver: '>=0'
        cname: ''
        jekyll_baseurl: ''
        jekyll_cfg: _config.yml
        jekyll_src: _site
        pre_build_commands: ''
        provider: github
        repository: ''
        token: ${{ secrets.GH_TOKEN }}
name: Build and Deploy to Github Pages
on:
  repository_dispatch:
    types: trigger-ga___main.yml
